spring:
  application:
    name: okr-be
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:
    username: sa
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      pool-name: Hikari
      auto-commit: false
      minimum-idle: 10
      maximum-pool-size: 100
      max-lifetime: 170000
      connection-timeout: 30000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  flyway:
    enabled: true
    table: 'okr_flyway_schema_history'
    locations: classpath:db/migrations

google:
  client-id:
  client-secret:
  redirect-uri:
  scope:

frontend:
  url: http://localhost:5173
jwt:
  secret:

springdoc:
  swagger-ui:
    path: /swagger-ui

app:
  cors:
    allowed-credentials: true
    allowed-origins: '*'

server:
  port: 7777
  servlet:
    context-path: /okr-api/v1
  compression:
    enabled: true
    mime-types: text/html;text/plain;text/css;application/javascript;application/json
    min-response-size: 1024